feat: use svg underlines icon and fix target blank links
mondora/mondora-website-front pull request #136
Opened 2019-10-10 08:46 UTC by luzzif

2019-10-10 10:29 UTC, manuelserradev requested changes

2019-10-10 10:29 UTC, nitroin commented on src/pages/index.jsx
> +                    href={"https://bcalmbcorp.com/"}
Prop `href="https://bcalmbcorp.com/"`.

2019-10-10 12:22 UTC, leopuleo requested changes
Possiamo aggiungere `rel="noopener noreferrer"` anche ai link nel piede?

2019-10-10 14:36 UTC, manuelserradev approved these changes

2019-10-10 14:50 UTC, leopuleo approved these changes

2019-10-10 14:51 UTC, fumaluca approved these changes

2019-10-11 08:17 UTC, jgosatti commented on src/components/instagram-post/index.jsx
> +    display: ${props => (props.index < "6" ? "block" : "none")};
ma questo controllo in base all'index cosa rappresenta?

2019-10-11 08:19 UTC, jgosatti approved these changes

2019-10-11 08:55 UTC, ChiaraCism approved these changes

2019-10-11 09:31 UTC, jgosatti approved these changes

2019-10-11 10:24 UTC, rampazzof approved these changes

2019-10-11 10:25 UTC, merged